declare const IPROOV_SELFIE = "tradle.IProovSelfie";
declare const SELFIE = "tradle.Selfie";
declare const PHOTO_ID = "tradle.PhotoID";
declare const ADDRESS = "tradle.OnfidoAddress";
declare const APPLICANT = "tradle.OnfidoApplicant";
declare const EMAIL_ADDRESS = "tradle.EmailAddress";
declare const NAME = "tradle.Name";
declare const VERIFICATION = "tradle.Verification";
declare const APPLICATION = "tradle.Application";
declare const DEFAULT_WEBHOOK_KEY = "onfido_webhook";
declare const ONFIDO_WEBHOOK_EVENTS: string[];
declare const DEFAULT_WEBHOOK_EVENTS: string[];
export { IPROOV_SELFIE, SELFIE, PHOTO_ID, ADDRESS, APPLICANT, EMAIL_ADDRESS, NAME, VERIFICATION, APPLICATION, DEFAULT_WEBHOOK_KEY, ONFIDO_WEBHOOK_EVENTS, DEFAULT_WEBHOOK_EVENTS };
