declare const IPROOV_SELFIE = "tradle.IProovSelfie";
declare const SELFIE = "tradle.Selfie";
declare const PHOTO_ID = "tradle.PhotoID";
declare const ADDRESS = "tradle.onfido.Address";
declare const APPLICANT = "tradle.onfido.Applicant";
declare const EMAIL_ADDRESS = "tradle.EmailAddress";
declare const NAME = "tradle.Name";
declare const VERIFICATION = "tradle.Verification";
declare const APPLICATION = "tradle.Application";
declare const PG_PERSONAL_DETAILS = "tradle.pg.PersonalDetails";
declare const DEFAULT_WEBHOOK_KEY = "onfido_webhook";
declare const ONFIDO_WEBHOOK_EVENTS: string[];
declare const DEFAULT_WEBHOOK_EVENTS: string[];
declare const REPORTS: any;
declare const DEFAULT_REPORTS: any;
declare const PROPERTY_SETS: {
    name: string[];
    dob: string[];
    address: string[];
};
export { IPROOV_SELFIE, SELFIE, PHOTO_ID, ADDRESS, APPLICANT, EMAIL_ADDRESS, NAME, VERIFICATION, APPLICATION, PG_PERSONAL_DETAILS, DEFAULT_WEBHOOK_KEY, ONFIDO_WEBHOOK_EVENTS, DEFAULT_WEBHOOK_EVENTS, REPORTS, DEFAULT_REPORTS, PROPERTY_SETS };
