"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const IPROOV_SELFIE = 'tradle.IProovSelfie';
exports.IPROOV_SELFIE = IPROOV_SELFIE;
const SELFIE = 'tradle.Selfie';
exports.SELFIE = SELFIE;
const PHOTO_ID = 'tradle.PhotoID';
exports.PHOTO_ID = PHOTO_ID;
const ADDRESS = 'tradle.OnfidoAddress';
exports.ADDRESS = ADDRESS;
const APPLICANT = 'tradle.OnfidoApplicant';
exports.APPLICANT = APPLICANT;
const EMAIL_ADDRESS = 'tradle.EmailAddress';
exports.EMAIL_ADDRESS = EMAIL_ADDRESS;
const NAME = 'tradle.Name';
exports.NAME = NAME;
const VERIFICATION = 'tradle.Verification';
exports.VERIFICATION = VERIFICATION;
const APPLICATION = 'tradle.Application';
exports.APPLICATION = APPLICATION;
const ONFIDO_WEBHOOK_KEY = 'onfido_webhook';
exports.ONFIDO_WEBHOOK_KEY = ONFIDO_WEBHOOK_KEY;
//# sourceMappingURL=constants.js.map